{% set version = "0.14.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-arrow
  version: {{ version|replace("-", "_") }}

source:
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/apache-arrow-{{ version }}.tar.gz
  sha256: 71e668e1901a06211d3f7ab6b6c7cb80ab1c81bb0d22885be42b74782e953470

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - pkg-config
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}make
    - {{posix}}zip               # [win]
  host:
    - r-base
    - arrow-cpp {{ version }}
    - r-r6
    - r-rcpp >=1.0.1
    - r-assertthat
    - r-bit64
    - r-fs
    - r-purrr
    - r-rlang
    - r-tidyselect
  run:
    - r-base
    - {{ pin_compatible('arrow-cpp') }}
    - {{native}}gcc-libs         # [win]
    - r-r6
    - r-rcpp >=1.0.1
    - r-assertthat
    - r-bit64
    - r-fs
    - r-purrr
    - r-rlang
    - r-tidyselect

test:
  commands:
    - $R -e "library('arrow')"           # [not win]
    - "\"%R%\" -e \"library('arrow')\""  # [win]

about:
  home: https://github.com/apache/arrow
  license: Apache 2.0
  summary: R Integration to 'Apache' 'Arrow'.
  license_family: APACHE

extra:
  recipe-maintainers:
    - conda-forge/r
    - conda-forge/arrow-cpp

# Package: arrow
# Title: Integration to 'Apache' 'Arrow'
# Version: 0.14.0
# Authors@R: c( person("Romain", "Fran\u00e7ois", email = "romain@rstudio.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-2444-4226")), person("Jeroen", "Ooms", email = "jeroen@berkeley.edu", role = c("aut")), person("Neal", "Richardson", email = "neal@ursalabs.org", role = c("aut")), person("Javier", "Luraschi", email = "javier@rstudio.com", role = c("ctb")), person("Jeffrey", "Wong", email = "jeffreyw@netflix.com", role = c("ctb")), person("Apache Arrow", email = "dev@arrow.apache.org", role = c("aut", "cph")) )
# Description: 'Apache' 'Arrow' <https://arrow.apache.org/> is a cross-language development platform for in-memory data. It specifies a standardized language-independent columnar memory format for flat and hierarchical data, organized for efficient analytic operations on modern hardware. This package provides an interface to the Arrow C++ library.
# Depends: R (>= 3.1)
# License: Apache License (>= 2.0)
# URL: https://github.com/apache/arrow/
# BugReports: https://issues.apache.org/jira/projects/ARROW/issues
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# SystemRequirements: C++11
# LinkingTo: Rcpp (>= 1.0.1)
# Imports: assertthat, bit64, fs, purrr, R6, Rcpp (>= 1.0.1), rlang, tidyselect, utils
# Roxygen: list(markdown = TRUE)
# RoxygenNote: 6.1.1
# Suggests: covr, hms, lubridate, pkgdown, rmarkdown, roxygen2, testthat, tibble, vctrs
# Collate: 'enums.R' 'R6.R' 'ArrayData.R' 'ChunkedArray.R' 'Column.R' 'Field.R' 'List.R' 'RecordBatch.R' 'RecordBatchReader.R' 'RecordBatchWriter.R' 'Schema.R' 'Struct.R' 'Table.R' 'array.R' 'arrow-package.R' 'arrowExports.R' 'buffer.R' 'io.R' 'compression.R' 'compute.R' 'csv.R' 'dictionary.R' 'feather.R' 'install-arrow.R' 'json.R' 'memory_pool.R' 'message.R' 'parquet.R' 'read_record_batch.R' 'read_table.R' 'reexports-bit64.R' 'reexports-tidyselect.R' 'write_arrow.R'
