# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "G0LTaUwpq7RofZnSkfBsJ12lY68aDdxJE+KvKVoEu/0+AJsSq1YvL//NML7Mxbxb/6NaQdyfVHsTQf+ixxg1wTEj5wvegPJ2vJolKgYnpT3pu+ApRkhray3BxrtAGKe65jA+uilMnFJAN59b6QLZUoCOWzYGg/aEU30Gg9IZlokskd7o1/Mv9MQSx1gMm+z60IANeuK1/2fVTl/k+KN8Cre2smBvVp0mQ43Ethj0vzme//q6T4c5m6E9JoAI01yxUnqim3xZ4bupgeDN4cJyjO9Zll4Q2AwzZOnp1Q9pcbzWgFfZSnphv6iLVs6yJ0wqveuQ/yGkVNGqqrF5EF/gHepQxu29EmlpTs7yAhub+BUFagtHlbXAb50UW1R5o33kiMOP1jLZfadT1nwOLJW2lBdUWIGqsjWBabuO+uSViKjQfPTHxtBweBryb/c+jJ8WkwjQflf0O049iIb1/UcYvKUBWjo6yb/gQ4Bji1usIZTd/2l5YPSy2RuQryIiQLI2NaRaB4U8Etq7O4EHtTKG7P9QpTl08lE8ws+MNn+59rzTWQMPXbCJwVKHf3Gjy1TdvuzqFlOG76uxi+1AqyCZe+TmPs1UmYiSqXL6J5eXsKEI5oO3mwXe/dOeu4J8nTKBkOEst0GNHDNLprbAerzSDFxhdcN3Yvl1ne/ibMwyUWw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml